# Location Selection

In [23]:
from desdeo.problem import Constant, Variable, Problem, Objective, VariableTypeEnum, Constraint, TensorConstant, TensorVariable, ConstraintTypeEnum
import numpy as np
import pandas as pd
from slugify import slugify
import folium
# These are to just suppress warnings in the outputs of the example
import warnings

warnings.filterwarnings("ignore")

## Model inputs

In [24]:

# Mininum expected attendance to be worth visiting 
min_att = 15

# Cost constants
# The current gas costs ($/gallon)
raw_dollars_per_gallon = 3.00

# The efficiency of the vehicle (miles/gallon)
raw_mpg = 6.0
# How long the event is (hours)
hours_per_event = 4
driver_salary_per_hour = 19
raw_driver_cost_per_trip = hours_per_event * driver_salary_per_hour

# Food desert threshold (miles) (TODO this should be in minutes)
raw_food_desert_threshold = 15

## Helper functions

## Load and process Constants

In [25]:


home = "Ada"
# Read the adjacency matrix (distance in miles)
adjDist = pd.read_csv("../data/adjacencyMatrixDist.csv", index_col=0)
dist2home = adjDist.loc[:,[home]].rename(columns={home:"dist2home"})
dist2home.index.name = "city"
display("Distance to home base")
display(dist2home)

# Read the adjacency matrix (travel time in minutes)
adjTTime = pd.read_csv("../data/adjacencyMatrixTravelTime.csv", index_col=0)
display("Travel time adjacency matrix")
display(adjTTime)

# Read the cities 
cities = pd.read_csv("../data/cities.csv")
events = pd.read_csv("../data/events.csv")

'Distance to home base'

                dist2home
city
Ada                  0.00
Alger                8.81
Bluffton            19.50
Cairo               31.26
Caledonia          102.21
Carey               66.05
Columbus Grove      36.16
Continental         70.66
Cridersville        38.76
Delphos             51.03
Dunkirk             17.85
Elida               44.79
Forest              35.97
Fort Jennings       57.86
Glandorf            50.50
Kalida              52.05
Kenton              24.99
La Rue              52.09
Leipsic             48.76
Lima                26.28
Marion              91.69
Minster             84.84
Mount Victory       39.74
Nevada              71.70
New Bremen          79.50
New Knoxville       69.38
Ottawa              47.60
Ottoville           60.42
Pandora             35.75
Prospect            78.84
Saint Marys         69.13
Spencerville        49.06
Sycamore            68.87
Upper Sandusky      53.51
Wapakoneta          50.39
Waynesfield         34.99

'Travel time adjacency matrix'

,Ada,Alger,Bluffton,Cairo,Caledonia,Carey,Columbus Grove,Continental,Cridersville,Delphos,...,Ottawa,Ottoville,Pandora,Prospect,Saint Marys,Spencerville,Sycamore,Upper Sandusky,Wapakoneta,Waynesfield
Ada,0.00,9.30,20.48,23.63,70.40,45.55,31.78,62.73,35.73,35.74,...,41.59,42.32,31.00,72.88,51.50,50.39,51.19,38.63,39.70,32.14
Alger,9.30,0.00,29.61,32.76,79.53,54.68,40.91,71.86,36.43,44.88,...,50.72,51.45,37.84,73.76,52.20,51.39,60.32,47.76,40.39,22.95
Bluffton,20.48,29.61,0.00,18.42,76.23,36.78,20.55,49.98,29.81,30.53,...,26.52,37.11,15.30,84.11,45.58,45.18,56.07,44.46,33.78,37.66
Cairo,23.63,32.76,18.42,0.00,78.76,51.34,11.29,42.34,26.10,17.40,...,19.81,23.98,20.73,86.64,43.96,32.74,59.54,46.98,32.15,37.08
Caledonia,70.40,79.53,76.23,78.76,0.00,47.25,87.77,118.71,95.99,91.73,...,96.46,98.31,86.98,28.59,111.76,107.07,49.45,34.24,99.96,90.16
Carey,45.55,54.68,36.78,51.34,47.25,0.00,57.96,78.84,63.76,64.48,...,55.38,71.06,48.79,53.68,79.53,79.13,19.29,15.77,67.73,71.61
Columbus Grove,31.78,40.91,20.55,11.29,87.77,57.96,0.00,32.45,35.78,27.08,...,9.92,28.86,9.43,94.52,53.64,42.42,67.42,54.87,41.84,46.76
Continental,62.73,71.86,49.98,42.34,118.71,78.84,32.45,0.00,63.28,36.13,...,23.51,26.32,41.28,126.22,74.44,52.23,97.36,86.57,69.34,74.72
Cridersville,35.73,36.43,29.81,26.10,95.99,63.76,35.78,63.28,0.00,36.77,...,44.46,43.35,35.31,101.02,28.29,30.89,74.39,61.84,16.48,27.29
Delphos,35.74,44.88,30.53,17.40,91.73,64.48,27.08,36.13,36.77,0.00,...,35.47,10.96,36.38,99.67,39.11,16.90,72.58,60.02,39.91,48.70
Dunkirk,18.74,27.87,26.69,29.21,59.40,33.70,37.09,68.80,44.07,42.25,...,47.69,48.42,37.10,64.92,61.88,57.18,40.22,27.67,50.07,50.14
Elida,35.72,39.09,30.50,17.23,91.70,64.45,26.91,47.81,24.93,14.07,...,35.59,21.85,36.18,100.05,42.63,22.80,72.96,60.40,30.52,36.73
Forest,27.32,36.46,33.15,35.68,51.67,25.98,43.56,75.27,50.53,48.72,...,53.77,54.51,43.18,55.06,67.96,63.27,32.69,20.14,56.16,53.77
Fort Jennings,43.19,52.32,37.97,24.84,99.17,71.92,24.18,26.77,44.21,10.26,...,28.09,5.28,33.62,107.12,48.57,26.36,80.02,67.47,49.38,56.14
Glandorf,45.77,54.89,31.63,23.99,101.58,60.49,14.10,24.74,48.64,36.88,...,5.16,27.83,22.93,108.50,66.33,52.98,79.01,68.85,54.53,59.46
Kalida,43.13,52.26,37.91,24.30,99.11,70.10,22.78,19.60,43.68,22.69,...,14.77,13.63,32.21,106.62,61.00,38.79,79.52,66.97,49.73,55.12
Kenton,24.45,25.33,42.95,45.47,56.63,45.61,53.35,85.06,54.52,58.51,...,63.95,64.68,53.36,48.70,64.04,69.76,52.32,39.59,52.98,33.80
La Rue,50.69,51.56,66.02,68.55,40.17,50.21,76.42,108.13,80.76,81.58,...,86.64,87.38,76.05,25.93,90.28,96.00,52.56,34.57,79.21,60.03
Leipsic,48.20,57.33,29.78,32.32,96.62,55.53,22.43,25.95,56.94,47.98,...,13.49,40.91,21.90,103.90,73.64,63.45,74.05,65.99,61.84,65.72
Lima,26.32,28.07,21.10,12.31,87.28,55.05,22.00,49.95,14.94,23.93,...,30.99,30.34,26.80,92.98,32.44,24.60,65.89,53.33,20.63,25.35
Marion,63.48,65.53,69.31,71.84,15.84,38.88,79.71,111.42,86.69,84.87,...,89.53,91.37,80.04,16.59,104.82,100.13,42.51,27.31,93.02,75.64
Minster,67.17,67.87,61.26,59.63,127.44,95.21,69.31,92.29,43.96,56.95,...,77.11,67.86,66.60,103.18,18.00,40.06,105.68,93.12,32.90,48.83
Mount Victory,39.20,40.07,57.87,60.39,59.07,60.28,68.27,99.98,69.27,73.43,...,78.87,79.61,68.28,34.67,73.98,84.51,67.00,54.27,62.92,46.77
Nevada,48.33,57.46,54.16,56.68,36.09,23.73,64.56,96.27,71.53,69.72,...,74.23,76.08,64.75,43.25,89.53,84.84,18.97,13.53,77.72,79.89
New Bremen,61.95,62.65,56.04,54.41,122.22,89.99,64.09,87.17,38.74,51.83,...,72.05,62.74,61.54,97.95,12.88,34.94,100.62,88.07,27.77,43.77
New Knoxville,56.91,57.61,51.00,49.37,117.17,84.95,59.05,84.40,33.70,49.07,...,66.84,59.98,56.33,99.92,11.83,32.17,95.41,82.86,19.68,38.06
Ottawa,41.59,50.72,26.52,19.81,96.46,55.38,9.92,23.51,44.46,35.47,...,0.00,28.40,17.82,103.75,62.16,50.94,73.90,64.67,50.35,55.28
Ottoville,42.32,51.45,37.11,23.98,98.31,71.06,28.86,26.32,43.35,10.96,...,28.40,0.00,38.29,105.71,50.02,27.80,78.62,66.06,49.36,54.74
Pandora,31.00,37.84,15.30,20.73,86.98,48.79,9.43,41.28,35.31,36.38,...,17.82,38.29,0.00,92.56,52.01,51.61,65.46,52.90,40.21,44.09
Prospect,72.88,73.76,84.11,86.64,28.59,53.68,94.52,126.22,101.02,99.67,...,103.75,105.71,92.56,0.00,102.56,114.42,56.80,41.60,91.50,80.23
Saint Marys,51.50,52.20,45.58,43.96,111.76,79.53,53.64,74.44,28.29,39.11,...,62.16,50.02,52.01,102.56,0.00,22.21,90.79,78.23,15.05,33.43
Spencerville,50.39,51.39,45.18,32.74,107.07,79.13,42.42,52.23,30.89,16.90,...,50.94,27.80,51.61,114.42,22.21,0.00,87.72,75.16,25.43,45.41
Sycamore,51.19,60.32,56.07,59.54,49.45,19.29,67.42,97.36,74.39,72.58,...,73.90,78.62,65.46,56.80,90.79,87.72,0.00,18.05,80.92,83.08
Upper Sandusky,38.63,47.76,44.46,46.98,34.24,15.77,54.87,86.57,61.84,60.02,...,64.67,66.06,52.90,41.60,78.23,75.16,18.05,0.00,67.50,69.67
Wapakoneta,39.70,40.39,33.78,32.15,99.96,67.73,41.84,69.34,16.48,39.91,...,50.35,49.36,40.21,91.50,15.05,25.43,80.92,67.50,0.00,21.86
Waynesfield,32.14,22.95,37.66,37.08,90.16,71.61,46.76,74.72,27.29,48.70,...,55.28,54.74,44.09,80.23,33.43,45.41,83.08,69.67,21.86,0.00

### Event table

In [26]:
# Create event table
events = pd.merge(cities, events, on="city")
events.loc[:,"expectedAttendance"] = (events.loc[:,"pop"] * events.loc[:,"attendanceRate"]).astype(int)

events.loc[:, "event_id"] = events.apply(lambda row: slugify(f'{row["city"]} {row["site"]} {no_nan(row["event"])}'), axis=1)
events.loc[:, "event_pretty"] = events.apply(lambda row: f'{row["site"]} {no_nan(row["event"])}', axis=1)

# Add the distance to home for each event 
events = pd.merge(events, dist2home, on="city")

display(events)

,city,lat,long,pop,site,event,attendanceRate,dow,startTime,endTime,EventDuration,wom,Notes,expectedAttendance,event_id,event_pretty,dist2home
0,Ada,40.768056,-83.825278,5334,Public Library,NaN,0.002,*,900,1800,2.0,*,NaN,10,ada-public-library,Public Library,0.00
1,Alger,40.709722,-83.844167,837,Community Center,Food Commodities,0.002,Wednesday,900,1100,2.0,3,Wednesday after the third Tuesday each month (...,1,alger-community-center-food-commodities,Community Center Food Commodities,8.81
2,Alger,40.709722,-83.844167,837,Community Center,Community Dinner,0.002,Wednesday,1630,1830,2.0,4,Fourth Wednesday of each month,1,alger-community-center-community-dinner,Community Center Community Dinner,8.81
3,Bluffton,40.889444,-83.879167,3967,Bluffton Public Library,NaN,0.002,Thursday,900,1100,2.0,*,Bluffton Public Library,7,bluffton-bluffton-public-library,Bluffton Public Library,19.50
4,Cairo,40.830833,-84.084444,517,Public Library,NaN,0.002,*,900,1800,2.0,*,NaN,1,cairo-public-library,Public Library,31.26
5,Delphos,40.861111,-84.350000,7117,Public Library,NaN,0.002,*,900,1800,2.0,*,NaN,14,delphos-public-library,Public Library,51.03
6,Dunkirk,40.788056,-83.642778,774,HN Community Center,Community Meal,0.002,Tuesday,1630,1800,1.5,4,Fourth Wednesday of each month,1,dunkirk-hn-community-center-community-meal,HN Community Center Community Meal,17.85
7,Elida,40.786667,-84.198889,1923,Public Library,NaN,0.002,*,900,1800,2.0,*,NaN,3,elida-public-library,Public Library,44.79
8,Forest,40.805000,-83.511667,1350,Public Library,NaN,0.002,*,900,1800,2.0,*,NaN,2,forest-public-library,Public Library,35.97
9,Kenton,40.646667,-83.622500,7947,Seton Hall,NaN,0.002,Tuesday,1130,1330,2.0,4,Fourth Tuesday of each month,15,kenton-seton-hall,Seton Hall,24.99
10,Kenton,40.646667,-83.622500,7947,Hardincrest,NaN,0.002,Thursday,900,1100,2.0,3,Third Thursday of each month,15,kenton-hardincrest,Hardincrest,24.99
11,Kenton,40.646667,-83.622500,7947,YMCA,NaN,0.002,Wednesday,900,1100,2.0,4,Fourth Wednesday every month,15,kenton-ymca,YMCA,24.99
12,Lima,40.746389,-84.123333,35579,Mercy Health Thrift,NaN,0.002,Tuesday,1130,1330,2.0,1,First Tuesday of each month,71,lima-mercy-health-thrift,Mercy Health Thrift,26.28
13,Lima,40.746389,-84.123333,35579,Habitat For Humanity,NaN,0.002,Thursday,1030,1230,2.0,1,First Thursday of each month,71,lima-habitat-for-humanity,Habitat For Humanity,26.28
14,Lima,40.746389,-84.123333,35579,Our Daily Bread,NaN,0.002,Tuesday,1130,1300,2.0,3,Third Tuesday of each month,71,lima-our-daily-bread,Our Daily Bread,26.28
15,Lima,40.746389,-84.123333,35579,St. Mark’s Methodist,Community Meal,0.002,Wednesday,1630,1830,2.0,3,Third Wednesday of each month,71,lima-st-marks-methodist-community-meal,St. Mark’s Methodist Community Meal,26.28
16,Lima,40.746389,-84.123333,35579,Christian Corner Community Center,NaN,0.002,Wednesday,900,1100,2.0,1,First Wednesday of each month,71,lima-christian-corner-community-center,Christian Corner Community Center,26.28
17,Mount Victory,40.533611,-83.521111,601,Public Library,NaN,0.002,*,900,1800,2.0,*,NaN,1,mount-victory-public-library,Public Library,39.74

### Close cities for events

In [27]:

close_cities = adjTTime < raw_food_desert_threshold
event2city = events.loc[:,["city", "event_id"]].merge(close_cities, left_on="city", right_index=True)
display(event2city)
event2city = (event2city.iloc[:,2:].values).astype(int)
e_adj_raw = event2city.T
display(event2city.T.shape)
e_adj_raw_list = e_adj_raw.tolist()
e_adj_raw_list

,city,event_id,Ada,Alger,Bluffton,Cairo,Caledonia,Carey,Columbus Grove,Continental,...,Ottawa,Ottoville,Pandora,Prospect,Saint Marys,Spencerville,Sycamore,Upper Sandusky,Wapakoneta,Waynesfield
0,Ada,ada-public-library,True,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,Alger,alger-community-center-food-commodities,True,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,Alger,alger-community-center-community-dinner,True,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,Bluffton,bluffton-bluffton-public-library,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,Cairo,cairo-public-library,False,False,False,True,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
5,Delphos,delphos-public-library,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
6,Dunkirk,dunkirk-hn-community-center-community-meal,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,Elida,elida-public-library,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,Forest,forest-public-library,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,Kenton,kenton-seton-hall,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,Kenton,kenton-hardincrest,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,Kenton,kenton-ymca,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,Lima,lima-mercy-health-thrift,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,Lima,lima-habitat-for-humanity,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,Lima,lima-our-daily-bread,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15,Lima,lima-st-marks-methodist-community-meal,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16,Lima,lima-christian-corner-community-center,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17,Mount Victory,mount-victory-public-library,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

(36, 18)

[[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0],
 [0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [28]:
event_dist2home = events.loc[:,["dist2home"]].T.values
event_dist2home_list = event_dist2home.tolist()

## Constants

In [29]:
event_count = events.shape[0]

# Expected attenance 
raw_attendance = events.loc[:,["expectedAttendance"]] 
raw_over_attendance = (raw_attendance < min_att).astype(int)

# How many people to expect to attend each event
ea = TensorConstant(name="Expected attendance",
                                 symbol="ea", 
                                 type="int",
                                 shape=raw_attendance.T.shape,
                                 values=raw_attendance.T.values.tolist())
display(ea)

# How many events are expected to be over attended? 
eoa = TensorConstant(name="Expected over attendance", 
                    symbol="eoa", 
                    type="integer",
                    shape=raw_over_attendance.T.shape,
                    values=raw_over_attendance.T.values.tolist())

display(eoa)

# Distance to home 
ed2h = TensorConstant(name="The distance to drive from home to event", 
                    symbol="ed2h", 
                    type="real",
                    shape=event_dist2home.shape,
                    values=event_dist2home_list)
display(ed2h)

mpg = Constant(name="Miles per gallon (miles/gallon)", 
               symbol="mpg", 
               type="real",
               value=raw_mpg)

display(mpg)
dpg = Constant(name="Dollars per gallon ($/gallon)", 
               symbol="dpg", 
               type="real",
               value=raw_dollars_per_gallon)

display(dpg)
dcpt = Constant(name="Driver cost per trip ($)", 
                                symbol="dcpt", 
                                type="real", 
                                value=raw_driver_cost_per_trip)

display(dcpt)

# Event adjacency to cities
e_adj = TensorConstant(name="Event adjacency to cities", 
                      symbol="e_adj", 
                      shape=e_adj_raw.shape,
                      values=e_adj_raw_list)
display(e_adj)

city_pops = TensorConstant(name="City populations", 
                           symbol="cpop", 
                           shape=[cities.shape[0],1],
                           values=cities.loc[:,["pop"]].values.tolist()
                           )

display(city_pops)

total_pop = Constant(name="Total population of interest", 
                     symbol="tpop", 
                     type="real",
                     value=float(sum(cities.loc[:,"pop"])))

display(total_pop)

TensorConstant(name='Expected attendance', symbol='ea', shape=[1, 18], values=['List', ['List', 10, 1, 1, 7, 1, 14, 1, 3, 2, 15, 15, 15, 71, 71, 71, 71, 71, 1]])

TensorConstant(name='Expected over attendance', symbol='eoa', shape=[1, 18], values=['List', ['List', 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

TensorConstant(name='The distance to drive from home to event', symbol='ed2h', shape=[1, 18], values=['List', ['List', 0.0, 8.81, 8.81, 19.5, 31.26, 51.03, 17.85, 44.79, 35.97, 24.99, 24.99, 24.99, 26.28, 26.28, 26.28, 26.28, 26.28, 39.74]])

Constant(name='Miles per gallon (miles/gallon)', symbol='mpg', value=6.0)

Constant(name='Dollars per gallon ($/gallon)', symbol='dpg', value=3.0)

Constant(name='Driver cost per trip ($)', symbol='dcpt', value=76)

TensorConstant(name='Event adjacency to cities', symbol='e_adj', shape=[36, 18], values=['List', ['List', 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0], ['List', 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0], ['List', 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

TensorConstant(name='City populations', symbol='cpop', shape=[36, 1], values=['List', ['List', 5334], ['List', 837], ['List', 3967], ['List', 517], ['List', 560], ['List', 3565], ['List', 2160], ['List', 1102], ['List', 1791], ['List', 7117], ['List', 774], ['List', 1923], ['List', 1350], ['List', 525], ['List', 969], ['List', 1455], ['List', 7947], ['List', 676], ['List', 2177], ['List', 35579], ['List', 35999], ['List', 3046], ['List', 601], ['List', 706], ['List', 3034], ['List', 946], ['List', 4456], ['List', 966], ['List', 1204], ['List', 1067], ['List', 8397], ['List', 2198], ['List', 793], ['List', 6698], ['List', 9957], ['List', 749]])

Constant(name='Total population of interest', symbol='tpop', value=161142.0)

## Variables

In [30]:
ev = TensorVariable(
  name="Events visited",
  symbol="ev",
  variable_type=VariableTypeEnum.integer,
  shape=[events.shape[0],1],
  lowerbounds=0,
  upperbounds=1,
  initial_value=0)

display(ev)

cover = TensorVariable(
    name="Coverage of cities",
    symbol="cover", 
    variable_type=VariableTypeEnum.integer,
    shape=[adjTTime.shape[0],1],
    lowerbounds=0,
    upperbounds=1,
    initial_values=0)

cover

TensorVariable(name='Events visited', symbol='ev', variable_type=<VariableTypeEnum.integer: 'integer'>, shape=[18, 1], lowerbounds=0, upperbounds=1, initial_values=None)

TensorVariable(name='Coverage of cities', symbol='cover', variable_type=<VariableTypeEnum.integer: 'integer'>, shape=[36, 1], lowerbounds=0, upperbounds=1, initial_values=0)

## Constraints

In [31]:
# ev = [18, 1]
# cover [28, 1]
# e_adj [28, 18]
# [28, 18] . [18, 1] = [28, 1]


g = Constraint(
      name="Desert constraint",
      symbol="c",
      func="cover-e_adj@ev",
      cons_type=ConstraintTypeEnum.LTE,
      is_convex=False,
      is_linear=True,
      is_twice_differentiable=True)

## Objective

In [32]:
# Total patients seen 
total_patients = Objective(
    name = "Maximize total patients visited",
    symbol = "f_1", 
    maximize = True,
    is_twice_differentiable=True,
    func = "Sum(ea@ev)"
)

# Overstaffed events
over_staffed_events = Objective(
    name = "Minimize the number of overstaffed events",
    symbol = "f_2",
    maximize = False,
    is_twice_differentiable=True,
    func = "Sum(eoa@ev)"
)

# Cost of events
costs = Objective(
    name = "Minimize costs",
    symbol = "f_3",
    maximize = False,
    is_twice_differentiable=True,
    func = "(Sum(ed2h@ev)/mpg)*dpg + Sum(ev)*dcpt"
)


# cpop: [1, 28]
# cover: [28, 1]
# 
coverage = Objective(
    name = "Maximize coverage of region", 
    symbol = "f_4", 
    maximize = True, 
    is_twice_differentiable=True,
    func = "Sum(cover*cpop)/tpop"
)

## Problem

In [33]:
prob = Problem(
        name="Simple site selection",
        description="Simple implementation of the site selection problem",
        type="linear",
        constraints=[g],
        constants=[eoa, ea, ed2h, mpg, dpg, dcpt, e_adj, city_pops, total_pop],
        variables=[ev, cover],
        objectives=[total_patients, over_staffed_events, costs, coverage]
    )

## Ideal/nadir

In [34]:
# f_1 ideal is seeing all patients, nadir is seeing no patients
all_patients = int(np.sum(events.loc[:,"expectedAttendance"]))

# f_2 ideal is having no over staffed events
# f_2 naird is having visiting all locations with over staffed events
all_ose = int(np.sum(raw_over_attendance))


# How many miles are driven/gas costs
max_dist = events.loc[:,"dist2home"].sum()
total_gas_cost = (max_dist / raw_mpg) * raw_dollars_per_gallon
driver_cost = events.shape[0]*raw_driver_cost_per_trip
max_costs = float(driver_cost + total_gas_cost)

prob = prob.update_ideal_and_nadir(
    new_ideal={
        "f_1": all_patients,
        "f_2": 0, 
        "f_3": 0, 
        "f_4": 1.0
        }, 
    new_nadir={
        "f_1": 0,
        "f_2": all_ose,
        "f_3": max_costs, 
        "f_4": 0
        }
    )


print(f"Ideal values: {prob.get_ideal_point()}")
print(f"Nadir values: {prob.get_nadir_point()}")

Ideal values: {'f_1': 441, 'f_2': 0, 'f_3': 0, 'f_4': 1.0}
Nadir values: {'f_1': 0, 'f_2': 10, 'f_3': 1600.065, 'f_4': 0}

## RPM solver

In [35]:
from desdeo.mcdm.reference_point_method import rpm_solve_solutions
from itertools import product

ref_resolution = 2

f_1_ref = np.linspace(prob.get_ideal_point()["f_1"], prob.get_nadir_point()["f_1"],ref_resolution).tolist()
f_2_ref = np.linspace(prob.get_ideal_point()["f_2"], prob.get_nadir_point()["f_2"],ref_resolution).tolist()
f_3_ref = np.linspace(prob.get_ideal_point()["f_3"], prob.get_nadir_point()["f_3"],ref_resolution).tolist()
f_4_ref = np.linspace(prob.get_ideal_point()["f_4"], prob.get_nadir_point()["f_4"],ref_resolution).tolist()

pf_samples_raw = []
i = 0 
for ref in product(f_1_ref, f_2_ref, f_3_ref, f_4_ref):
    reference_point = {"f_1": ref[0], "f_2": ref[1], "f_3": ref[2], "f_4": ref[3]}

    print(f"Calculating for ref #{i} {reference_point}")
    try: 
        res = rpm_solve_solutions(prob, reference_point=reference_point)
        pf_samples_raw.append(res)
    except ValueError:
        print("Error running for that ref.")
    i += 1

Calculating for ref #0 {'f_1': 441.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 1.0}
Calculating for ref #1 {'f_1': 441.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 0.0}
Calculating for ref #2 {'f_1': 441.0, 'f_2': 0.0, 'f_3': 1600.065, 'f_4': 1.0}
Calculating for ref #3 {'f_1': 441.0, 'f_2': 0.0, 'f_3': 1600.065, 'f_4': 0.0}
Calculating for ref #4 {'f_1': 441.0, 'f_2': 10.0, 'f_3': 0.0, 'f_4': 1.0}
Calculating for ref #5 {'f_1': 441.0, 'f_2': 10.0, 'f_3': 0.0, 'f_4': 0.0}
Calculating for ref #6 {'f_1': 441.0, 'f_2': 10.0, 'f_3': 1600.065, 'f_4': 1.0}
Calculating for ref #7 {'f_1': 441.0, 'f_2': 10.0, 'f_3': 1600.065, 'f_4': 0.0}
Calculating for ref #8 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 1.0}
Calculating for ref #9 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 0.0}
Calculating for ref #10 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 1600.065, 'f_4': 1.0}
Calculating for ref #11 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 1600.065, 'f_4': 0.0}
Calculating for ref #12 {'f_1': 0.0, 'f_2': 10.0, 'f_3': 0.0, 'f_4': 1.0}
Calculating for ref #13 {'f_1': 0.0, 'f_2': 10.0, 'f_3': 0.0, 'f_4': 0.0}
Calculating for ref #14 {'f_1': 0.0, 'f_2': 10.0, 'f_3': 1600.065, 'f_4': 1.0}
Calculating for ref #15 {'f_1': 0.0, 'f_2': 10.0, 'f_3': 1600.065, 'f_4': 0.0}

## Send relevant data to a pkl file

In [39]:
import pickle
output = open(f'../data/pf_{ref_resolution**4}.pkl', 'wb')
pickle.dump({"pf": pf_samples_raw,
             "prob" : prob,
             "cities": cities,
             "events": events,
             "event2city": event2city
             }, output)