# Location selection

In [362]:
from desdeo.problem import Constant, Variable, Problem, Objective, VariableTypeEnum, Constraint, TensorConstant, TensorVariable, ConstraintTypeEnum
import numpy as np

# These are to just suppress warnings in the outputs of the example
import warnings

warnings.filterwarnings("ignore")

## Model inputs

In [363]:
# Mininum expected attendance to be worth visiting 
min_att = 15

# Cost constants
# The current gas costs ($/gallon)
raw_dollars_per_gallon = 3.00

# The efficiency of the vehicle (miles/gallon)
raw_mpg = 6.0
# How long the event is (hours)
hours_per_event = 4
driver_salary_per_hour = 19
raw_driver_cost_per_trip = hours_per_event * driver_salary_per_hour

# Food desert threshold (miles) (TODO this should be in minutes)
raw_food_desert_threshold = 15

## Load and process constants

In [364]:
from slugify import slugify
import pandas as pd

def no_nan(val):
    if pd.isna(val):
        return ""
    else:
        return str(val)

home = "Ada"
# Read the adjacency matrix (distance in miles)
adjDist = pd.read_csv("adjacencyMatrixDist.csv", index_col=0)
dist2home = adjDist.loc[:,[home]].rename(columns={home:"dist2home"})
dist2home.index.name = "city"
display(dist2home)

# Read the adjacency matrix (travel time in minutes)
adjTTime = pd.read_csv("adjacencyMatrixTravelTime.csv", index_col=0)
display(adjTTime)

# Read the cities 
cities = pd.read_csv("cities.csv")
events = pd.read_csv("events.csv")

               dist2home
city
Ada                  0.0
Lima                16.2
Kenton              15.5
Delphos             31.8
Bluffton            12.0
Spencerville        30.8
Elida               23.5
Forest              18.4
Alger                5.4
Dunkirk             10.6
Mount Victory       24.7
Cairo               18.6
St. Marys           43.0

,Ada,Alger,Bluffton,Cairo,Columbus Grove,Continental,Cridersville,Delphos,Dunkirk,Elida,...,Mount Victory,New Bremen,New Knoxville,Ottawa,Ottoville,Pandora,Saint Marys,Spencerville,Wapakoneta,Waynesfield
Ada,0,9,16,20,25,48,28,34,16,30,...,34,52,46,34,37,26,45,43,36,25
Alger,9,0,22,26,31,54,29,40,20,35,...,33,53,46,40,43,32,46,45,36,19
Bluffton,16,22,0,17,15,39,25,31,23,27,...,48,49,42,23,34,13,42,40,32,32
Cairo,21,26,17,0,15,39,20,18,27,13,...,48,44,38,17,34,13,37,26,28,28
Columbus Grove,26,31,15,9,0,26,26,24,32,20,...,57,50,43,9,22,8,43,34,33,33
Continental,48,53,40,30,25,0,49,30,54,33,...,80,68,64,19,21,32,58,42,56,56
Cridersville,28,29,25,21,26,49,0,29,39,17,...,49,30,23,35,34,30,23,18,13,17
Delphos,34,39,31,18,24,30,29,0,40,12,...,66,40,35,32,11,33,30,14,33,42
Dunkirk,16,20,23,27,32,54,39,41,0,36,...,28,63,56,41,44,33,56,50,46,36
Elida,30,35,26,13,21,33,17,12,36,0,...,61,41,33,28,17,29,32,16,24,33
Forest,24,29,27,31,36,59,44,45,13,41,...,27,68,61,46,48,38,61,54,51,41
Fort Jennings,35,40,32,18,19,21,33,11,41,16,...,66,49,43,24,5,27,39,23,39,43
Glandorf,39,44,26,20,13,16,39,31,45,30,...,70,63,56,5,22,17,55,43,46,47
Kalida,34,39,26,17,11,14,36,20,40,22,...,65,57,52,12,11,20,48,32,43,42
Kenton,19,18,34,38,44,66,39,52,15,48,...,14,58,51,52,55,44,51,55,41,18
Leipsic,38,44,23,29,21,20,42,43,45,40,...,69,67,60,13,34,17,60,54,50,49
Lima,23,23,20,12,20,39,16,26,35,12,...,49,40,33,28,29,25,33,23,23,22
Minster,56,56,53,48,54,73,34,45,66,45,...,63,6,13,62,55,57,16,31,26,39
Mount Victory,31,30,46,50,56,78,49,65,27,60,...,0,60,58,64,67,56,57,64,48,34
New Bremen,52,52,49,45,50,67,30,39,63,40,...,60,0,9,59,49,53,10,25,22,35
New Knoxville,45,45,42,38,43,63,24,35,56,33,...,56,10,0,52,44,46,10,22,14,28
Ottawa,36,41,23,17,10,18,36,32,42,29,...,66,60,53,0,23,14,52,42,43,43
Ottoville,37,42,34,21,22,21,35,11,43,18,...,67,49,44,23,0,30,40,24,21,32
Pandora,27,32,12,18,9,32,29,33,33,30,...,57,53,46,14,30,0,46,43,37,35
Saint Marys,45,45,42,38,43,58,23,30,56,31,...,57,9,10,52,41,46,0,16,15,28
Spencerville,42,42,39,26,34,42,18,14,49,16,...,64,26,22,41,24,42,16,0,21,32
Wapakoneta,35,35,32,28,33,56,12,33,46,25,...,48,23,15,43,22,37,15,22,0,18
Waynesfield,25,19,32,28,33,56,17,43,36,32,...,34,35,29,42,32,34,28,32,18,0

In [365]:

# Create event table
events = pd.merge(cities, events, on="city")
events.loc[:,"expectedAttendance"] = (events.loc[:,"pop"] * events.loc[:,"attendanceRate"]).astype(int)

events.loc[:, "event_id"] = events.apply(lambda row: slugify(f'{row["city"]} {row["site"]} {no_nan(row["event"])}'), axis=1)

# Add the distance to home for each event 
events = pd.merge(events, dist2home, on="city")

events

,city,lat,long,pop,site,event,attendanceRate,expectedAttendance,event_id,dist2home
0,Ada,40.768056,-83.825278,5334,Public Library,NaN,0.002,10,ada-public-library,0.0
1,Lima,40.746389,-84.123333,35579,Mercy Health Thrift,NaN,0.002,71,lima-mercy-health-thrift,16.2
2,Lima,40.746389,-84.123333,35579,Habitat For Humanity,NaN,0.002,71,lima-habitat-for-humanity,16.2
3,Lima,40.746389,-84.123333,35579,Our Daily Bread,NaN,0.002,71,lima-our-daily-bread,16.2
4,Lima,40.746389,-84.123333,35579,St. Mark’s Methodist,Community Meal,0.002,71,lima-st-marks-methodist-community-meal,16.2
5,Lima,40.746389,-84.123333,35579,Christian Corner Community Center,NaN,0.002,71,lima-christian-corner-community-center,16.2
6,Kenton,40.646667,-83.622500,7947,Seton Hall,NaN,0.002,15,kenton-seton-hall,15.5
7,Kenton,40.646667,-83.622500,7947,Hardincrest,NaN,0.002,15,kenton-hardincrest,15.5
8,Kenton,40.646667,-83.622500,7947,YMCA,NaN,0.002,15,kenton-ymca,15.5
9,Delphos,40.861111,-84.350000,7117,Public Library,NaN,0.002,14,delphos-public-library,31.8
10,Bluffton,40.889444,-83.879167,3967,Bluffton Public Library,NaN,0.002,7,bluffton-bluffton-public-library,12.0
11,Elida,40.786667,-84.198889,1923,Public Library,NaN,0.002,3,elida-public-library,23.5
12,Forest,40.805000,-83.511667,1350,Public Library,NaN,0.002,2,forest-public-library,18.4
13,Alger,40.709722,-83.844167,837,Community Center,Food Commodities,0.002,1,alger-community-center-food-commodities,5.4
14,Alger,40.709722,-83.844167,837,Community Center,Community Dinner,0.002,1,alger-community-center-community-dinner,5.4
15,Dunkirk,40.788056,-83.642778,774,HN Community Center,Community Meal,0.002,1,dunkirk-hn-community-center-community-meal,10.6
16,Mount Victory,40.533611,-83.521111,601,Public Library,NaN,0.002,1,mount-victory-public-library,24.7
17,Cairo,40.830833,-84.084444,517,Public Library,NaN,0.002,1,cairo-public-library,18.6

### Close cities

In [366]:
close_cities = adjTTime < raw_food_desert_threshold

# Constants

In [367]:
event_count = events.shape[0]

# Expected attenance 
raw_attendance = events.loc[:,"expectedAttendance"] 
raw_over_attendance = raw_attendance < min_att

# Expected attendance 
exp_att = []
# Over staffed events (ose)
ose = []
# Distance to home
d2h = []

# Close cities
cc = []

for e in range(event_count): 

    # TODO change the simple numbers to event ids
    city = events.loc[e,"city"]
    event_id = events.loc[e,"event_id"]

    exp_att.append(Constant(name=f"Expected attendance: {event_id}", 
                        symbol=f"exp_att_{e}", 
                        type="int", 
                        value=raw_attendance[e]
                        ))

    ose.append(Constant(name=f"Over attendance: {event_id}", 
                        symbol=f"ose_{e}", 
                        type="binary",
                        value=raw_over_attendance[e]))

    d2h.append(Constant(name=f"Distance to home: {event_id}", 
                              symbol=f"d2h_{e}", 
                              type="real", 
                              value=dist2home.loc[city]
                              ))

    cc.append(TensorConstant(name=f"Close cities: {event_id}", 
                       symbol=f"cc_{e}",
                       type="integer",
                       shape=[close_cities.shape[0]],
                       values=(close_cities.loc[:,city].values).astype(int).tolist()
                    ))    


mpg = Constant(name="Miles per gallon (miles/gallon)", 
               symbol="mpg", 
               type="real",
               value=raw_mpg)

dpg = Constant(name="Dollars per gallon ($/gallon)", 
               symbol="dpg", 
               type="real",
               value=raw_dollars_per_gallon)

driver_cost_per_trip = Constant(name="Driver cost per trip ($)", 
                                symbol="dcpt", 
                                type="real", 
                                value=raw_driver_cost_per_trip)


food_desert_threshold = Constant(name="Food desert threshold (miles)", 
                                 symbol="fdt", 
                                 type="real",
                                 value=raw_food_desert_threshold
                                 )
cc

[TensorConstant(name='Close cities: ada-public-library', symbol='cc_0', shape=[28], values=['List', 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 TensorConstant(name='Close cities: lima-mercy-health-thrift', symbol='cc_1', shape=[28], values=['List', 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 TensorConstant(name='Close cities: lima-habitat-for-humanity', symbol='cc_2', shape=[28], values=['List', 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 TensorConstant(name='Close cities: lima-our-daily-bread', symbol='cc_3', shape=[28], values=['List', 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 TensorConstant(name='Close cities: lima-st-marks-methodist-community-meal', symbol='cc_4', shape=[28], values=['List', 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 TensorConstant(name='Close cities: lima-christian-corner-community-center', symbol='cc_5', shape=[28], values=['List', 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 TensorConstant(name='Close cities: kenton-seton-hall', symbol='cc_6', shape=[28], values=['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 TensorConstant(name='Close cities: kenton-hardincrest', symbol='cc_7', shape=[28], values=['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 TensorConstant(name='Close cities: kenton-ymca', symbol='cc_8', shape=[28], values=['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 TensorConstant(name='Close cities: delphos-public-library', symbol='cc_9', shape=[28], values=['List', 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0]),
 TensorConstant(name='Close cities: bluffton-bluffton-public-library', symbol='cc_10', shape=[28], values=['List', 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 TensorConstant(name='Close cities: elida-public-library', symbol='cc_11', shape=[28], values=['List', 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 TensorConstant(name='Close cities: forest-public-library', symbol='cc_12', shape=[28], values=['List', 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 TensorConstant(name='Close cities: alger-community-center-food-commodities', symbol='cc_13', shape=[28], values=['List', 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 TensorConstant(name='Close cities: alger-community-center-community-dinner', symbol='cc_14', shape=[28], values=['List', 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 TensorConstant(name='Close cities: dunkirk-hn-community-center-community-meal', symbol='cc_15', shape=[28], values=['List', 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 TensorConstant(name='Close cities: mount-victory-public-library', symbol='cc_16', shape=[28], values=['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 TensorConstant(name='Close cities: cairo-public-library', symbol='cc_17', shape=[28], values=['List', 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])]

## Constraints
Making a helper constraint to model an boolean OR operation

| $x_{Ada}$ | $x_{Lima_1}$ | $x_{Lima_2}$ | $z$ |
| --------- | ------------ | ------------ | --- |
| 1         | 1            | 1            | 1   |
| 1         | 1            | 0            | 1   |
| 1         | 0            | 1            | 1   |
| 1         | 0            | 0            | 1   |
| 0         | 1            | 1            | 1   |
| 0         | 1            | 0            | 1   |
| 0         | 0            | 1            | 1   |
| 0         | 0            | 0            | 0   |

Constraints to add: 

$z \ge x_{Ada}$, or  $0 \ge x_{Ada} - z$

$z \ge x_{Lima_1}$, or $0 \ge x_{Lima_1} - z$

$z \ge x_{Lima_2}$, or $0 \ge x_{Lima_2} - z$

$z \le \sum{x_i}$, or $z - (\sum{x_i}) \le 0 $

In [368]:
desert_or_constr_exprs = []

for e in range(events.shape[0]): 
    desert_or_constr_exprs.append(
        f"evt_visit_{e} * cc_{e} - z"
    )

final_const_exprs = " + ".join([f"event_visit_{e} * cc_{e}" for e in range(events.shape[0]) ]) 
final_const_exprs = f"z-({final_const_exprs})"



desert_or_constr_exprs.append(final_const_exprs)
desert_or_constr_exprs

desert_or_constr_exprs

['evt_visit_0 * cc_0 - z',
 'evt_visit_1 * cc_1 - z',
 'evt_visit_2 * cc_2 - z',
 'evt_visit_3 * cc_3 - z',
 'evt_visit_4 * cc_4 - z',
 'evt_visit_5 * cc_5 - z',
 'evt_visit_6 * cc_6 - z',
 'evt_visit_7 * cc_7 - z',
 'evt_visit_8 * cc_8 - z',
 'evt_visit_9 * cc_9 - z',
 'evt_visit_10 * cc_10 - z',
 'evt_visit_11 * cc_11 - z',
 'evt_visit_12 * cc_12 - z',
 'evt_visit_13 * cc_13 - z',
 'evt_visit_14 * cc_14 - z',
 'evt_visit_15 * cc_15 - z',
 'evt_visit_16 * cc_16 - z',
 'evt_visit_17 * cc_17 - z',
 'z-(event_visit_0 * cc_0 + event_visit_1 * cc_1 + event_visit_2 * cc_2 + event_visit_3 * cc_3 + event_visit_4 * cc_4 + event_visit_5 * cc_5 + event_visit_6 * cc_6 + event_visit_7 * cc_7 + event_visit_8 * cc_8 + event_visit_9 * cc_9 + event_visit_10 * cc_10 + event_visit_11 * cc_11 + event_visit_12 * cc_12 + event_visit_13 * cc_13 + event_visit_14 * cc_14 + event_visit_15 * cc_15 + event_visit_16 * cc_16 + event_visit_17 * cc_17)']

In [369]:
constraints = []
for (e, expr) in enumerate(desert_or_constr_exprs): 
  constraints.append(
    Constraint(
      name=f"Desert constraint #{e}",
      symbol=f"ds_{e}",
      func=expr,
      cons_type=ConstraintTypeEnum.LTE,
      is_convex=False,
      is_linear=True,
      is_twice_differentiable=True)
)

## Variables
Generate one variable per event

In [370]:
# Main variables (visit event, or don't visit event)

evt_visited = []
for e in range(event_count):
  evt_visited.append(Variable(
    name=events.loc[e, "event_id"],
    symbol=f"evt_visit_{e}",
    variable_type=VariableTypeEnum.integer,
    lowerbound=0,
    upperbound=1,
    initial_value=0))
  
# Auxiliary variables 
aux_desert_var = TensorVariable(
  name="Desert auxiliary variable",
  symbol="z",
  variable_type=VariableTypeEnum.integer,
  shape=[close_cities.shape[0]],
  lowerbounds=0,
  upperbounds=events.shape[0]
)
aux_desert_var

TensorVariable(name='Desert auxiliary variable', symbol='z', variable_type=<VariableTypeEnum.integer: 'integer'>, shape=[28], lowerbounds=0, upperbounds=18, initial_values=None)

## Objectives

### Build the objective expression strings

In [371]:
# total patients served
obj_func_total_patients = " + ".join([f"evt_visit_{e} * exp_att_{e}" for e in range(event_count)])
display(obj_func_total_patients)

'evt_visit_0 * exp_att_0 + evt_visit_1 * exp_att_1 + evt_visit_2 * exp_att_2 + evt_visit_3 * exp_att_3 + evt_visit_4 * exp_att_4 + evt_visit_5 * exp_att_5 + evt_visit_6 * exp_att_6 + evt_visit_7 * exp_att_7 + evt_visit_8 * exp_att_8 + evt_visit_9 * exp_att_9 + evt_visit_10 * exp_att_10 + evt_visit_11 * exp_att_11 + evt_visit_12 * exp_att_12 + evt_visit_13 * exp_att_13 + evt_visit_14 * exp_att_14 + evt_visit_15 * exp_att_15 + evt_visit_16 * exp_att_16 + evt_visit_17 * exp_att_17'

In [372]:

# ose = over staffed events
obj_func_ose = " + ".join([f"evt_visit_{e} * ose_{e}" for e in range(event_count)])
display(obj_func_ose)

'evt_visit_0 * ose_0 + evt_visit_1 * ose_1 + evt_visit_2 * ose_2 + evt_visit_3 * ose_3 + evt_visit_4 * ose_4 + evt_visit_5 * ose_5 + evt_visit_6 * ose_6 + evt_visit_7 * ose_7 + evt_visit_8 * ose_8 + evt_visit_9 * ose_9 + evt_visit_10 * ose_10 + evt_visit_11 * ose_11 + evt_visit_12 * ose_12 + evt_visit_13 * ose_13 + evt_visit_14 * ose_14 + evt_visit_15 * ose_15 + evt_visit_16 * ose_16 + evt_visit_17 * ose_17'

In [373]:
# Total costs
total_distance = " + ".join([f"evt_visit_{e} * d2h_{e}" for e in range(event_count)])
print("Total distance:")
display(total_distance)

print("Total gas cost")
total_gas_costs = f"(({total_distance})/mpg)*dpg"
display(total_gas_costs)

# TODO I can represent the drive time of the driver here once I have the drive distance matrix
print("Total driver cost")
total_driver_cost = " + ".join([f"evt_visit_{e}" for e in range(event_count)])
total_driver_cost = f"({total_driver_cost})*dcpt"

display(total_driver_cost)

print("Total costs")
obj_total_cost = f"{total_gas_costs} + {total_driver_cost}"
display(obj_total_cost)

Total distance:

'evt_visit_0 * d2h_0 + evt_visit_1 * d2h_1 + evt_visit_2 * d2h_2 + evt_visit_3 * d2h_3 + evt_visit_4 * d2h_4 + evt_visit_5 * d2h_5 + evt_visit_6 * d2h_6 + evt_visit_7 * d2h_7 + evt_visit_8 * d2h_8 + evt_visit_9 * d2h_9 + evt_visit_10 * d2h_10 + evt_visit_11 * d2h_11 + evt_visit_12 * d2h_12 + evt_visit_13 * d2h_13 + evt_visit_14 * d2h_14 + evt_visit_15 * d2h_15 + evt_visit_16 * d2h_16 + evt_visit_17 * d2h_17'

Total gas cost

'((evt_visit_0 * d2h_0 + evt_visit_1 * d2h_1 + evt_visit_2 * d2h_2 + evt_visit_3 * d2h_3 + evt_visit_4 * d2h_4 + evt_visit_5 * d2h_5 + evt_visit_6 * d2h_6 + evt_visit_7 * d2h_7 + evt_visit_8 * d2h_8 + evt_visit_9 * d2h_9 + evt_visit_10 * d2h_10 + evt_visit_11 * d2h_11 + evt_visit_12 * d2h_12 + evt_visit_13 * d2h_13 + evt_visit_14 * d2h_14 + evt_visit_15 * d2h_15 + evt_visit_16 * d2h_16 + evt_visit_17 * d2h_17)/mpg)*dpg'

Total driver cost

'(evt_visit_0 + evt_visit_1 + evt_visit_2 + evt_visit_3 + evt_visit_4 + evt_visit_5 + evt_visit_6 + evt_visit_7 + evt_visit_8 + evt_visit_9 + evt_visit_10 + evt_visit_11 + evt_visit_12 + evt_visit_13 + evt_visit_14 + evt_visit_15 + evt_visit_16 + evt_visit_17)*dcpt'

Total costs

'((evt_visit_0 * d2h_0 + evt_visit_1 * d2h_1 + evt_visit_2 * d2h_2 + evt_visit_3 * d2h_3 + evt_visit_4 * d2h_4 + evt_visit_5 * d2h_5 + evt_visit_6 * d2h_6 + evt_visit_7 * d2h_7 + evt_visit_8 * d2h_8 + evt_visit_9 * d2h_9 + evt_visit_10 * d2h_10 + evt_visit_11 * d2h_11 + evt_visit_12 * d2h_12 + evt_visit_13 * d2h_13 + evt_visit_14 * d2h_14 + evt_visit_15 * d2h_15 + evt_visit_16 * d2h_16 + evt_visit_17 * d2h_17)/mpg)*dpg + (evt_visit_0 + evt_visit_1 + evt_visit_2 + evt_visit_3 + evt_visit_4 + evt_visit_5 + evt_visit_6 + evt_visit_7 + evt_visit_8 + evt_visit_9 + evt_visit_10 + evt_visit_11 + evt_visit_12 + evt_visit_13 + evt_visit_14 + evt_visit_15 + evt_visit_16 + evt_visit_17)*dcpt'

### Create the objective objects

In [374]:

# Total patients visited 
total_patients = Objective(
    name = "Maximize total patients visited",
    symbol = "f_1", 
    maximize = True,
    is_twice_differentiable=True,
    func = obj_func_total_patients
)

# Overstaffed events
over_staffed_events = Objective(
    name = "Minimize the number of overstaffed events",
    symbol = "f_2",
    maximize = False,
    is_twice_differentiable=True,
    func = obj_func_ose
)

# Total costs
costs = Objective(
    name = "Minimize the total costs",
    symbol = "f_3",
    maximize = False,
    is_twice_differentiable=True,
    func = obj_total_cost
)

# Communities served
comm_served = Objective(
    name = "Maximize the number of communities served",
    symbol = "f_4",
    maximize = True,
    is_twice_differentiable=True,
    func = "Sum(z)"
)

## Problem

In [375]:
 

prob = Problem(
        name="Simple site selection",
        description="Simple implementation of the site selection problem",
        type="linear",
        constants=exp_att +  ose + d2h + cc + [mpg, dpg, driver_cost_per_trip, food_desert_threshold],
        variables=evt_visited + [aux_desert_var],
        objectives=[total_patients, over_staffed_events, costs, comm_served],
        constraints=constraints
    )

## Ideal/nadir

In [376]:
# f_1 ideal is seeing all patients, nadir is seeing no patients
all_patients = int(np.sum(events.loc[:,"expectedAttendance"]))

# f_2 ideal is having no over staffed events
# f_2 naird is having visiting all locations with over staffed events
all_ose = int(np.sum(raw_over_attendance))

# f_3 ideal is no costs
# f_3 nadir is going to every site

# How many miles are driven/gas costs
max_dist = events.loc[:,"dist2home"].sum()
total_gas_cost = (max_dist / raw_mpg) * raw_dollars_per_gallon
driver_cost = events.shape[0]*raw_driver_cost_per_trip
max_costs = float(driver_cost + total_gas_cost)

# f_4 ideal is all cities, nadir no cities


prob = prob.update_ideal_and_nadir(
    new_ideal={
        "f_1": all_patients,
        "f_2": 0,
        "f_3": 0,
        "f_4": len(adjTTime.index)
        }, 
    new_nadir={
        "f_1": 0,
        "f_2": all_ose,
        "f_3": max_costs,
        "f_4": 0
        }
    )

print(f"Ideal values: {prob.get_ideal_point()}")
print(f"Nadir values: {prob.get_nadir_point()}")

Ideal values: {'f_1': 441, 'f_2': 0, 'f_3': 0, 'f_4': 28}
Nadir values: {'f_1': 0, 'f_2': 10, 'f_3': 1506.95, 'f_4': 0}

## Solve (with NSGA-III)!

In [ ]:
from desdeo.emo.methods.EAs import nsga3_mixed_integer


solver, publisher = nsga3_mixed_integer(problem=prob)

result = solver()

### Clean up NSGA-III results

In [ ]:
pf_obj = (result.outputs.to_pandas()).astype(int).loc[:,["f_1", "f_2", "f_3"]]
pf_dec = (result.solutions.to_pandas()).astype(bool)

results = pd.DataFrame(pf_obj.values, 
                       columns=["Total Patients Served", "Number of over staffed events", "Total Costs"])

# Build string lists for the events visited
pf_events_visited = []
for (e, ev) in pf_dec.iterrows(): 
    events_visited = ev.values
    pf_events_visited.append("\n".join(events.loc[events_visited, "event_id"].values))


results.loc[:,"events_visited"] = pf_events_visited

results = results.drop_duplicates()

results

## Plot plot plot

In [ ]:
%matplotlib qt

from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

x = results.loc[:,"Total Patients Served"].values
y = results.loc[:,"Number of over staffed events"].values
z = results.loc[:,"Total Costs"].values

fig = plt.figure(figsize=(6, 6))
ax = fig.add_subplot(111, projection='3d')
scatter = ax.scatter(x, y, z,
           linewidths=1, alpha=.7,
           edgecolor='k',
           s = 200)

ax.set_xlabel("Total patients served")
ax.set_ylabel("Number of over staffed events")
ax.set_zlabel("Total costs")

#cbar = plt.colorbar(scatter, ax=ax, pad=0.1)
#cbar.set_label('Total Travel Costs ($)')  # Label for the color bar

plt.show()

## Solve! (with reference point method)

In [378]:
from desdeo.mcdm.reference_point_method import rpm_solve_solutions

reference_point = {"f_1": 200, "f_2": 2, "f_3": 1000, "f_4": 20}
display(prob)
results = rpm_solve_solutions(prob, reference_point=reference_point)

Problem(name='Simple site selection', description='Simple implementation of the site selection problem', constants=[Constant(name='Expected attendance: ada-public-library', symbol='exp_att_0', value=10.0), Constant(name='Expected attendance: lima-mercy-health-thrift', symbol='exp_att_1', value=71.0), Constant(name='Expected attendance: lima-habitat-for-humanity', symbol='exp_att_2', value=71.0), Constant(name='Expected attendance: lima-our-daily-bread', symbol='exp_att_3', value=71.0), Constant(name='Expected attendance: lima-st-marks-methodist-community-meal', symbol='exp_att_4', value=71.0), Constant(name='Expected attendance: lima-christian-corner-community-center', symbol='exp_att_5', value=71.0), Constant(name='Expected attendance: kenton-seton-hall', symbol='exp_att_6', value=15.0), Constant(name='Expected attendance: kenton-hardincrest', symbol='exp_att_7', value=15.0), Constant(name='Expected attendance: kenton-ymca', symbol='exp_att_8', value=15.0), Constant(name='Expected attendance: delphos-public-library', symbol='exp_att_9', value=14.0), Constant(name='Expected attendance: bluffton-bluffton-public-library', symbol='exp_att_10', value=7.0), Constant(name='Expected attendance: elida-public-library', symbol='exp_att_11', value=3.0), Constant(name='Expected attendance: forest-public-library', symbol='exp_att_12', value=2.0), Constant(name='Expected attendance: alger-community-center-food-commodities', symbol='exp_att_13', value=1.0), Constant(name='Expected attendance: alger-community-center-community-dinner', symbol='exp_att_14', value=1.0), Constant(name='Expected attendance: dunkirk-hn-community-center-community-meal', symbol='exp_att_15', value=1.0), Constant(name='Expected attendance: mount-victory-public-library', symbol='exp_att_16', value=1.0), Constant(name='Expected attendance: cairo-public-library', symbol='exp_att_17', value=1.0), Constant(name='Over attendance: ada-public-library', symbol='ose_0', value=1.0), Constant(name='Over attendance: lima-mercy-health-thrift', symbol='ose_1', value=0.0), Constant(name='Over attendance: lima-habitat-for-humanity', symbol='ose_2', value=0.0), Constant(name='Over attendance: lima-our-daily-bread', symbol='ose_3', value=0.0), Constant(name='Over attendance: lima-st-marks-methodist-community-meal', symbol='ose_4', value=0.0), Constant(name='Over attendance: lima-christian-corner-community-center', symbol='ose_5', value=0.0), Constant(name='Over attendance: kenton-seton-hall', symbol='ose_6', value=0.0), Constant(name='Over attendance: kenton-hardincrest', symbol='ose_7', value=0.0), Constant(name='Over attendance: kenton-ymca', symbol='ose_8', value=0.0), Constant(name='Over attendance: delphos-public-library', symbol='ose_9', value=1.0), Constant(name='Over attendance: bluffton-bluffton-public-library', symbol='ose_10', value=1.0), Constant(name='Over attendance: elida-public-library', symbol='ose_11', value=1.0), Constant(name='Over attendance: forest-public-library', symbol='ose_12', value=1.0), Constant(name='Over attendance: alger-community-center-food-commodities', symbol='ose_13', value=1.0), Constant(name='Over attendance: alger-community-center-community-dinner', symbol='ose_14', value=1.0), Constant(name='Over attendance: dunkirk-hn-community-center-community-meal', symbol='ose_15', value=1.0), Constant(name='Over attendance: mount-victory-public-library', symbol='ose_16', value=1.0), Constant(name='Over attendance: cairo-public-library', symbol='ose_17', value=1.0), Constant(name='Distance to home: ada-public-library', symbol='d2h_0', value=0.0), Constant(name='Distance to home: lima-mercy-health-thrift', symbol='d2h_1', value=16.2), Constant(name='Distance to home: lima-habitat-for-humanity', symbol='d2h_2', value=16.2), Constant(name='Distance to home: lima-our-daily-bread', symbol='d2h_3', value=16.2), Constant(name='Distance to home: lima-st-marks-methodist-community-meal', symbol='d2h_4', value=16.2), Constant(name='Distance to home: lima-christian-corner-community-center', symbol='d2h_5', value=16.2), Constant(name='Distance to home: kenton-seton-hall', symbol='d2h_6', value=15.5), Constant(name='Distance to home: kenton-hardincrest', symbol='d2h_7', value=15.5), Constant(name='Distance to home: kenton-ymca', symbol='d2h_8', value=15.5), Constant(name='Distance to home: delphos-public-library', symbol='d2h_9', value=31.8), Constant(name='Distance to home: bluffton-bluffton-public-library', symbol='d2h_10', value=12.0), Constant(name='Distance to home: elida-public-library', symbol='d2h_11', value=23.5), Constant(name='Distance to home: forest-public-library', symbol='d2h_12', value=18.4), Constant(name='Distance to home: alger-community-center-food-commodities', symbol='d2h_13', value=5.4), Constant(name='Distance to home: alger-community-center-community-dinner', symbol='d2h_14', value=5.4), Constant(name='Distance to home: dunkirk-hn-community-center-community-meal', symbol='d2h_15', value=10.6), Constant(name='Distance to home: mount-victory-public-library', symbol='d2h_16', value=24.7), Constant(name='Distance to home: cairo-public-library', symbol='d2h_17', value=18.6), TensorConstant(name='Close cities: ada-public-library', symbol='cc_0', shape=[28], values=['List', 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), TensorConstant(name='Close cities: lima-mercy-health-thrift', symbol='cc_1', shape=[28], values=['List', 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), TensorConstant(name='Close cities: lima-habitat-for-humanity', symbol='cc_2', shape=[28], values=['List', 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), TensorConstant(name='Close cities: lima-our-daily-bread', symbol='cc_3', shape=[28], values=['List', 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), TensorConstant(name='Close cities: lima-st-marks-methodist-community-meal', symbol='cc_4', shape=[28], values=['List', 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), TensorConstant(name='Close cities: lima-christian-corner-community-center', symbol='cc_5', shape=[28], values=['List', 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), TensorConstant(name='Close cities: kenton-seton-hall', symbol='cc_6', shape=[28], values=['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]), TensorConstant(name='Close cities: kenton-hardincrest', symbol='cc_7', shape=[28], values=['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]), TensorConstant(name='Close cities: kenton-ymca', symbol='cc_8', shape=[28], values=['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]), TensorConstant(name='Close cities: delphos-public-library', symbol='cc_9', shape=[28], values=['List', 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0]), TensorConstant(name='Close cities: bluffton-bluffton-public-library', symbol='cc_10', shape=[28], values=['List', 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]), TensorConstant(name='Close cities: elida-public-library', symbol='cc_11', shape=[28], values=['List', 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), TensorConstant(name='Close cities: forest-public-library', symbol='cc_12', shape=[28], values=['List', 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), TensorConstant(name='Close cities: alger-community-center-food-commodities', symbol='cc_13', shape=[28], values=['List', 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), TensorConstant(name='Close cities: alger-community-center-community-dinner', symbol='cc_14', shape=[28], values=['List', 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), TensorConstant(name='Close cities: dunkirk-hn-community-center-community-meal', symbol='cc_15', shape=[28], values=['List', 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), TensorConstant(name='Close cities: mount-victory-public-library', symbol='cc_16', shape=[28], values=['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]), TensorConstant(name='Close cities: cairo-public-library', symbol='cc_17', shape=[28], values=['List', 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), Constant(name='Miles per gallon (miles/gallon)', symbol='mpg', value=6.0), Constant(name='Dollars per gallon ($/gallon)', symbol='dpg', value=3.0), Constant(name='Driver cost per trip ($)', symbol='dcpt', value=76), Constant(name='Food desert threshold (miles)', symbol='fdt', value=15)], variables=[Variable(name='ada-public-library', symbol='evt_visit_0', variable_type=<VariableTypeEnum.integer: 'integer'>, lowerbound=0, upperbound=1, initial_value=0), Variable(name='lima-mercy-health-thrift', symbol='evt_visit_1', variable_type=<VariableTypeEnum.integer: 'integer'>, lowerbound=0, upperbound=1, initial_value=0), Variable(name='lima-habitat-for-humanity', symbol='evt_visit_2', variable_type=<VariableTypeEnum.integer: 'integer'>, lowerbound=0, upperbound=1, initial_value=0), Variable(name='lima-our-daily-bread', symbol='evt_visit_3', variable_type=<VariableTypeEnum.integer: 'integer'>, lowerbound=0, upperbound=1, initial_value=0), Variable(name='lima-st-marks-methodist-community-meal', symbol='evt_visit_4', variable_type=<VariableTypeEnum.integer: 'integer'>, lowerbound=0, upperbound=1, initial_value=0), Variable(name='lima-christian-corner-community-center', symbol='evt_visit_5', variable_type=<VariableTypeEnum.integer: 'integer'>, lowerbound=0, upperbound=1, initial_value=0), Variable(name='kenton-seton-hall', symbol='evt_visit_6', variable_type=<VariableTypeEnum.integer: 'integer'>, lowerbound=0, upperbound=1, initial_value=0), Variable(name='kenton-hardincrest', symbol='evt_visit_7', variable_type=<VariableTypeEnum.integer: 'integer'>, lowerbound=0, upperbound=1, initial_value=0), Variable(name='kenton-ymca', symbol='evt_visit_8', variable_type=<VariableTypeEnum.integer: 'integer'>, lowerbound=0, upperbound=1, initial_value=0), Variable(name='delphos-public-library', symbol='evt_visit_9', variable_type=<VariableTypeEnum.integer: 'integer'>, lowerbound=0, upperbound=1, initial_value=0), Variable(name='bluffton-bluffton-public-library', symbol='evt_visit_10', variable_type=<VariableTypeEnum.integer: 'integer'>, lowerbound=0, upperbound=1, initial_value=0), Variable(name='elida-public-library', symbol='evt_visit_11', variable_type=<VariableTypeEnum.integer: 'integer'>, lowerbound=0, upperbound=1, initial_value=0), Variable(name='forest-public-library', symbol='evt_visit_12', variable_type=<VariableTypeEnum.integer: 'integer'>, lowerbound=0, upperbound=1, initial_value=0), Variable(name='alger-community-center-food-commodities', symbol='evt_visit_13', variable_type=<VariableTypeEnum.integer: 'integer'>, lowerbound=0, upperbound=1, initial_value=0), Variable(name='alger-community-center-community-dinner', symbol='evt_visit_14', variable_type=<VariableTypeEnum.integer: 'integer'>, lowerbound=0, upperbound=1, initial_value=0), Variable(name='dunkirk-hn-community-center-community-meal', symbol='evt_visit_15', variable_type=<VariableTypeEnum.integer: 'integer'>, lowerbound=0, upperbound=1, initial_value=0), Variable(name='mount-victory-public-library', symbol='evt_visit_16', variable_type=<VariableTypeEnum.integer: 'integer'>, lowerbound=0, upperbound=1, initial_value=0), Variable(name='cairo-public-library', symbol='evt_visit_17', variable_type=<VariableTypeEnum.integer: 'integer'>, lowerbound=0, upperbound=1, initial_value=0), TensorVariable(name='Desert auxiliary variable', symbol='z', variable_type=<VariableTypeEnum.integer: 'integer'>, shape=[28], lowerbounds=0, upperbounds=18, initial_values=None)], objectives=[Objective(name='Maximize total patients visited', symbol='f_1', unit=None, func=['Add', ['Multiply', 'evt_visit_0', 'exp_att_0'], ['Multiply', 'evt_visit_1', 'exp_att_1'], ['Multiply', 'evt_visit_2', 'exp_att_2'], ['Multiply', 'evt_visit_3', 'exp_att_3'], ['Multiply', 'evt_visit_4', 'exp_att_4'], ['Multiply', 'evt_visit_5', 'exp_att_5'], ['Multiply', 'evt_visit_6', 'exp_att_6'], ['Multiply', 'evt_visit_7', 'exp_att_7'], ['Multiply', 'evt_visit_8', 'exp_att_8'], ['Multiply', 'evt_visit_9', 'exp_att_9'], ['Multiply', 'evt_visit_10', 'exp_att_10'], ['Multiply', 'evt_visit_11', 'exp_att_11'], ['Multiply', 'evt_visit_12', 'exp_att_12'], ['Multiply', 'evt_visit_13', 'exp_att_13'], ['Multiply', 'evt_visit_14', 'exp_att_14'], ['Multiply', 'evt_visit_15', 'exp_att_15'], ['Multiply', 'evt_visit_16', 'exp_att_16'], ['Multiply', 'evt_visit_17', 'exp_att_17']], simulator_path=None, surrogates=None, maximize=True, ideal=441, nadir=0, objective_type=<ObjectiveTypeEnum.analytical: 'analytical'>, is_linear=False, is_convex=False, is_twice_differentiable=True, scenario_keys=None), Objective(name='Minimize the number of overstaffed events', symbol='f_2', unit=None, func=['Add', ['Multiply', 'evt_visit_0', 'ose_0'], ['Multiply', 'evt_visit_1', 'ose_1'], ['Multiply', 'evt_visit_2', 'ose_2'], ['Multiply', 'evt_visit_3', 'ose_3'], ['Multiply', 'evt_visit_4', 'ose_4'], ['Multiply', 'evt_visit_5', 'ose_5'], ['Multiply', 'evt_visit_6', 'ose_6'], ['Multiply', 'evt_visit_7', 'ose_7'], ['Multiply', 'evt_visit_8', 'ose_8'], ['Multiply', 'evt_visit_9', 'ose_9'], ['Multiply', 'evt_visit_10', 'ose_10'], ['Multiply', 'evt_visit_11', 'ose_11'], ['Multiply', 'evt_visit_12', 'ose_12'], ['Multiply', 'evt_visit_13', 'ose_13'], ['Multiply', 'evt_visit_14', 'ose_14'], ['Multiply', 'evt_visit_15', 'ose_15'], ['Multiply', 'evt_visit_16', 'ose_16'], ['Multiply', 'evt_visit_17', 'ose_17']], simulator_path=None, surrogates=None, maximize=False, ideal=0, nadir=10, objective_type=<ObjectiveTypeEnum.analytical: 'analytical'>, is_linear=False, is_convex=False, is_twice_differentiable=True, scenario_keys=None), Objective(name='Minimize the total costs', symbol='f_3', unit=None, func=['Add', ['Multiply', ['Divide', ['Add', ['Multiply', 'evt_visit_0', 'd2h_0'], ['Multiply', 'evt_visit_1', 'd2h_1'], ['Multiply', 'evt_visit_2', 'd2h_2'], ['Multiply', 'evt_visit_3', 'd2h_3'], ['Multiply', 'evt_visit_4', 'd2h_4'], ['Multiply', 'evt_visit_5', 'd2h_5'], ['Multiply', 'evt_visit_6', 'd2h_6'], ['Multiply', 'evt_visit_7', 'd2h_7'], ['Multiply', 'evt_visit_8', 'd2h_8'], ['Multiply', 'evt_visit_9', 'd2h_9'], ['Multiply', 'evt_visit_10', 'd2h_10'], ['Multiply', 'evt_visit_11', 'd2h_11'], ['Multiply', 'evt_visit_12', 'd2h_12'], ['Multiply', 'evt_visit_13', 'd2h_13'], ['Multiply', 'evt_visit_14', 'd2h_14'], ['Multiply', 'evt_visit_15', 'd2h_15'], ['Multiply', 'evt_visit_16', 'd2h_16'], ['Multiply', 'evt_visit_17', 'd2h_17']], 'mpg'], 'dpg'], ['Multiply', ['Add', 'evt_visit_0', 'evt_visit_1', 'evt_visit_2', 'evt_visit_3', 'evt_visit_4', 'evt_visit_5', 'evt_visit_6', 'evt_visit_7', 'evt_visit_8', 'evt_visit_9', 'evt_visit_10', 'evt_visit_11', 'evt_visit_12', 'evt_visit_13', 'evt_visit_14', 'evt_visit_15', 'evt_visit_16', 'evt_visit_17'], 'dcpt']], simulator_path=None, surrogates=None, maximize=False, ideal=0, nadir=1506.95, objective_type=<ObjectiveTypeEnum.analytical: 'analytical'>, is_linear=False, is_convex=False, is_twice_differentiable=True, scenario_keys=None), Objective(name='Maximize the number of communities served', symbol='f_4', unit=None, func=['Sum', 'z'], simulator_path=None, surrogates=None, maximize=True, ideal=28, nadir=0, objective_type=<ObjectiveTypeEnum.analytical: 'analytical'>, is_linear=False, is_convex=False, is_twice_differentiable=True, scenario_keys=None)], constraints=[Constraint(name='Desert constraint #0', symbol='ds_0', cons_type=<ConstraintTypeEnum.LTE: '<='>, func=['Add', ['Multiply', 'evt_visit_0', 'cc_0'], ['Negate', 'z']], simulator_path=None, surrogates=None, is_linear=True, is_convex=False, is_twice_differentiable=True, scenario_keys=None), Constraint(name='Desert constraint #1', symbol='ds_1', cons_type=<ConstraintTypeEnum.LTE: '<='>, func=['Add', ['Multiply', 'evt_visit_1', 'cc_1'], ['Negate', 'z']], simulator_path=None, surrogates=None, is_linear=True, is_convex=False, is_twice_differentiable=True, scenario_keys=None), Constraint(name='Desert constraint #2', symbol='ds_2', cons_type=<ConstraintTypeEnum.LTE: '<='>, func=['Add', ['Multiply', 'evt_visit_2', 'cc_2'], ['Negate', 'z']], simulator_path=None, surrogates=None, is_linear=True, is_convex=False, is_twice_differentiable=True, scenario_keys=None), Constraint(name='Desert constraint #3', symbol='ds_3', cons_type=<ConstraintTypeEnum.LTE: '<='>, func=['Add', ['Multiply', 'evt_visit_3', 'cc_3'], ['Negate', 'z']], simulator_path=None, surrogates=None, is_linear=True, is_convex=False, is_twice_differentiable=True, scenario_keys=None), Constraint(name='Desert constraint #4', symbol='ds_4', cons_type=<ConstraintTypeEnum.LTE: '<='>, func=['Add', ['Multiply', 'evt_visit_4', 'cc_4'], ['Negate', 'z']], simulator_path=None, surrogates=None, is_linear=True, is_convex=False, is_twice_differentiable=True, scenario_keys=None), Constraint(name='Desert constraint #5', symbol='ds_5', cons_type=<ConstraintTypeEnum.LTE: '<='>, func=['Add', ['Multiply', 'evt_visit_5', 'cc_5'], ['Negate', 'z']], simulator_path=None, surrogates=None, is_linear=True, is_convex=False, is_twice_differentiable=True, scenario_keys=None), Constraint(name='Desert constraint #6', symbol='ds_6', cons_type=<ConstraintTypeEnum.LTE: '<='>, func=['Add', ['Multiply', 'evt_visit_6', 'cc_6'], ['Negate', 'z']], simulator_path=None, surrogates=None, is_linear=True, is_convex=False, is_twice_differentiable=True, scenario_keys=None), Constraint(name='Desert constraint #7', symbol='ds_7', cons_type=<ConstraintTypeEnum.LTE: '<='>, func=['Add', ['Multiply', 'evt_visit_7', 'cc_7'], ['Negate', 'z']], simulator_path=None, surrogates=None, is_linear=True, is_convex=False, is_twice_differentiable=True, scenario_keys=None), Constraint(name='Desert constraint #8', symbol='ds_8', cons_type=<ConstraintTypeEnum.LTE: '<='>, func=['Add', ['Multiply', 'evt_visit_8', 'cc_8'], ['Negate', 'z']], simulator_path=None, surrogates=None, is_linear=True, is_convex=False, is_twice_differentiable=True, scenario_keys=None), Constraint(name='Desert constraint #9', symbol='ds_9', cons_type=<ConstraintTypeEnum.LTE: '<='>, func=['Add', ['Multiply', 'evt_visit_9', 'cc_9'], ['Negate', 'z']], simulator_path=None, surrogates=None, is_linear=True, is_convex=False, is_twice_differentiable=True, scenario_keys=None), Constraint(name='Desert constraint #10', symbol='ds_10', cons_type=<ConstraintTypeEnum.LTE: '<='>, func=['Add', ['Multiply', 'evt_visit_10', 'cc_10'], ['Negate', 'z']], simulator_path=None, surrogates=None, is_linear=True, is_convex=False, is_twice_differentiable=True, scenario_keys=None), Constraint(name='Desert constraint #11', symbol='ds_11', cons_type=<ConstraintTypeEnum.LTE: '<='>, func=['Add', ['Multiply', 'evt_visit_11', 'cc_11'], ['Negate', 'z']], simulator_path=None, surrogates=None, is_linear=True, is_convex=False, is_twice_differentiable=True, scenario_keys=None), Constraint(name='Desert constraint #12', symbol='ds_12', cons_type=<ConstraintTypeEnum.LTE: '<='>, func=['Add', ['Multiply', 'evt_visit_12', 'cc_12'], ['Negate', 'z']], simulator_path=None, surrogates=None, is_linear=True, is_convex=False, is_twice_differentiable=True, scenario_keys=None), Constraint(name='Desert constraint #13', symbol='ds_13', cons_type=<ConstraintTypeEnum.LTE: '<='>, func=['Add', ['Multiply', 'evt_visit_13', 'cc_13'], ['Negate', 'z']], simulator_path=None, surrogates=None, is_linear=True, is_convex=False, is_twice_differentiable=True, scenario_keys=None), Constraint(name='Desert constraint #14', symbol='ds_14', cons_t

AttributeError: 'FiniteScalarRangeSet' object has no attribute 'set_tuple'

In [ ]:
for i, result in enumerate(results):
    print(f"Solution {i+1}:")
    print(f"Objective function values \t\t {result.optimal_objectives}")
    print(f"Decision variable values \t\t {result.optimal_variables}")
    print(f"Constraint values \t\t\t {result.constraint_values}")
    print("---")

results

Solution 1:
Objective function values 		 {'f_1': 355.0, 'f_2': 0.0, 'f_3': 420.5}
Decision variable values 		 {'evt_visit_0': 0.0, 'evt_visit_1': 1.0, 'evt_visit_2': 1.0, 'evt_visit_3': 1.0, 'evt_visit_4': 1.0, 'evt_visit_5': 1.0, 'evt_visit_6': 0.0, 'evt_visit_7': 0.0, 'evt_visit_8': 0.0, 'evt_visit_9': 0.0, 'evt_visit_10': 0.0, 'evt_visit_11': 0.0, 'evt_visit_12': 0.0, 'evt_visit_13': 0.0, 'evt_visit_14': 0.0, 'evt_visit_15': 0.0, 'evt_visit_16': 0.0, 'evt_visit_17': 0.0, '_alpha': -0.19999998999000201}
Constraint values 			 {'f_1_con': -0.1514739321154993, 'f_2_con': 9.989999993909038e-09, 'f_3_con': -0.18455158744484873}
---
Solution 2:
Objective function values 		 {'f_1': 441.0, 'f_2': 10.0, 'f_3': 1506.95}
Decision variable values 		 {'evt_visit_0': 1.0, 'evt_visit_1': 1.0, 'evt_visit_2': 1.0, 'evt_visit_3': 1.0, 'evt_visit_4': 1.0, 'evt_visit_5': 1.0, 'evt_visit_6': 1.0, 'evt_visit_7': 1.0, 'evt_visit_8': 1.0, 'evt_visit_9': 1.0, 'evt_visit_10': 1.0, 'evt_visit_11': 1.0, 'evt_visit_12': 1.0, 'evt_visit_13': 1.0, 'evt_visit_14': 1.0, 'evt_visit_15': 1.0, 'evt_visit_16': 1.0, 'evt_visit_17': 1.0, '_alpha': 0.8137740431695482}
Constraint values 			 {'f_1_con': 1.8127740863960184e-08, 'f_2_con': -0.013774123169540076, 'f_3_con': -0.47736606701666184}
---
Solution 3:
Objective function values 		 {'f_1': 355.0, 'f_2': 0.0, 'f_3': 420.5}
Decision variable values 		 {'evt_visit_0': 0.0, 'evt_visit_1': 1.0, 'evt_visit_2': 1.0, 'evt_visit_3': 1.0, 'evt_visit_4': 1.0, 'evt_visit_5': 1.0, 'evt_visit_6': 0.0, 'evt_visit_7': 0.0, 'evt_visit_8': 0.0, 'evt_visit_9': 0.0, 'evt_visit_10': 0.0, 'evt_visit_11': 0.0, 'evt_visit_12': 0.0, 'evt_visit_13': 0.0, 'evt_visit_14': 0.0, 'evt_visit_15': 0.0, 'evt_visit_16': 0.0, 'evt_visit_17': 0.0, '_alpha': -0.3514739320955013}
Constraint values 			 {'f_1_con': 9.989999993909038e-09, 'f_2_con': -59.835956233749336, 'f_3_con': -0.033077645339349426}
---
Solution 4:
Objective function values 		 {'f_1': 400.0, 'f_2': 0.0, 'f_3': 671.75}
Decision variable values 		 {'evt_visit_0': 0.0, 'evt_visit_1': 1.0, 'evt_visit_2': 1.0, 'evt_visit_3': 1.0, 'evt_visit_4': 1.0, 'evt_visit_5': 1.0, 'evt_visit_6': 1.0, 'evt_visit_7': 1.0, 'evt_visit_8': 1.0, 'evt_visit_9': 0.0, 'evt_visit_10': 0.0, 'evt_visit_11': 0.0, 'evt_visit_12': 0.0, 'evt_visit_13': 0.0, 'evt_visit_14': 0.0, 'evt_visit_15': 0.0, 'evt_visit_16': 0.0, 'evt_visit_17': 0.0, '_alpha': -0.19999998999000201}
Constraint values 			 {'f_1_con': -0.25351474821064485, 'f_2_con': 9.989999993909038e-09, 'f_3_con': -0.41589593305321937}
---

[SolverResults(optimal_variables={'evt_visit_0': 0.0, 'evt_visit_1': 1.0, 'evt_visit_2': 1.0, 'evt_visit_3': 1.0, 'evt_visit_4': 1.0, 'evt_visit_5': 1.0, 'evt_visit_6': 0.0, 'evt_visit_7': 0.0, 'evt_visit_8': 0.0, 'evt_visit_9': 0.0, 'evt_visit_10': 0.0, 'evt_visit_11': 0.0, 'evt_visit_12': 0.0, 'evt_visit_13': 0.0, 'evt_visit_14': 0.0, 'evt_visit_15': 0.0, 'evt_visit_16': 0.0, 'evt_visit_17': 0.0, '_alpha': -0.19999998999000201}, optimal_objectives={'f_1': 355.0, 'f_2': 0.0, 'f_3': 420.5}, constraint_values={'f_1_con': -0.1514739321154993, 'f_2_con': 9.989999993909038e-09, 'f_3_con': -0.18455158744484873}, extra_func_values=None, scalarization_values={'_asf': -0.20000051593821658}, success=True, message="Pyomo solver status is: 'ok', with termination condition: 'optimal'."),
 SolverResults(optimal_variables={'evt_visit_0': 1.0, 'evt_visit_1': 1.0, 'evt_visit_2': 1.0, 'evt_visit_3': 1.0, 'evt_visit_4': 1.0, 'evt_visit_5': 1.0, 'evt_visit_6': 1.0, 'evt_visit_7': 1.0, 'evt_visit_8': 1.0, 'evt_visit_9': 1.0, 'evt_visit_10': 1.0, 'evt_visit_11': 1.0, 'evt_visit_12': 1.0, 'evt_visit_13': 1.0, 'evt_visit_14': 1.0, 'evt_visit_15': 1.0, 'evt_visit_16': 1.0, 'evt_visit_17': 1.0, '_alpha': 0.8137740431695482}, optimal_objectives={'f_1': 441.0, 'f_2': 10.0, 'f_3': 1506.95}, constraint_values={'f_1_con': 1.8127740863960184e-08, 'f_2_con': -0.013774123169540076, 'f_3_con': -0.47736606701666184}, extra_func_values=None, scalarization_values={'_asf': 0.8137750431694497}, success=True, message="Pyomo solver status is: 'ok', with termination condition: 'optimal'."),
 SolverResults(optimal_variables={'evt_visit_0': 0.0, 'evt_visit_1': 1.0, 'evt_visit_2': 1.0, 'evt_visit_3': 1.0, 'evt_visit_4': 1.0, 'evt_visit_5': 1.0, 'evt_visit_6': 0.0, 'evt_visit_7': 0.0, 'evt_visit_8': 0.0, 'evt_visit_9': 0.0, 'evt_visit_10': 0.0, 'evt_visit_11': 0.0, 'evt_visit_12': 0.0, 'evt_visit_13': 0.0, 'evt_visit_14': 0.0, 'evt_visit_15': 0.0, 'evt_visit_16': 0.0, 'evt_visit_17': 0.0, '_alpha': -0.3514739320955013}, optimal_objectives={'f_1': 355.0, 'f_2': 0.0, 'f_3': 420.5}, constraint_values={'f_1_con': 9.989999993909038e-09, 'f_2_con': -59.835956233749336, 'f_3_con': -0.033077645339349426}, extra_func_values=None, scalarization_values={'_asf': -0.35147445804371585}, success=True, message="Pyomo solver status is: 'ok', with termination condition: 'optimal'."),
 SolverResults(optimal_variables={'evt_visit_0': 0.0, 'evt_visit_1': 1.0, 'evt_visit_2': 1.0, 'evt_visit_3': 1.0, 'evt_visit_4': 1.0, 'evt_visit_5': 1.0, 'evt_visit_6': 1.0, 'evt_visit_7': 1.0, 'evt_visit_8': 1.0, 'evt_visit_9': 0.0, 'evt_visit_10': 0.0, 'evt_visit_11': 0.0, 'evt_visit_12': 0.0, 'evt_visit_13': 0.0, 'evt_visit_14': 0.0, 'evt_visit_15': 0.0, 'evt_visit_16': 0.0, 'evt_visit_17': 0.0, '_alpha': -0.19999998999000201}, optimal_objectives={'f_1': 400.0, 'f_2': 0.0, 'f_3': 671.75}, constraint_values={'f_1_con': -0.25351474821064485, 'f_2_con': 9.989999993909038e-09, 'f_3_con': -0.41589593305321937}, extra_func_values=None, scalarization_values={'_asf': -0.20000045125153684}, success=True, message="Pyomo solver status is: 'ok', with termination condition: 'optimal'.")]