## Playing around with attendance data

In [69]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt

cities = pd.read_csv("../data/cities.csv")

# I'm going to assume "trip" == "event"
events = pd.read_excel("../data/MHC Trip Summary.xlsx")
# Remove nans for city and site type 
events = events.dropna(subset=["City", "Site Types"])

# Remove rows that have only nan
nan2zero_cols = "All Women (not pregnant 18+)", "Pregnant Patients (all ages)", "Children 1-18 years", "All infants <1 year"
non_all_nan_rows = ~np.all(np.isnan(events.loc[:, nan2zero_cols].values), axis=1)
events = events.loc[non_all_nan_rows,:]

# Fill the remaining gaps with zeros
events.loc[:,nan2zero_cols] = events.loc[:,nan2zero_cols].fillna(0)


events = pd.merge(events, cities.loc[:,["city","pop"]], left_on="City", right_on="city")

# Split multi-valued items
events["Site Types"] = events["Site Types"].apply(lambda st : np.array(st.split(";")) )

# Total foot traffic calculation
events["Foot traffic"] = events["All Men"] + events["All Women (not pregnant 18+)"] + events["Pregnant Patients (all ages)"] + events["Children 1-18 years"] + events["All infants <1 year"]
 

display(events)

,Date,City,Physical location,Site Types,Latitude,Longitude,Organizer,Services offered,Total Pharmacists,Total APPE Students,...,Patients referred to Healthwise MC.1,Patients referred to other sites.1,Patients needing f/u.1,Patients who were seen at f/u.1,Patients not seen at f/u.1,New diagnosis noted at f/u.1,Interventions made at appointment.1,city,pop,Foot traffic
0,2024-08-02 00:00:00,Ottawa,Ottawa Schools,[Special Event],41.028836,-84.046572,HealthWise,BP + BG,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ottawa,4456,28.0
1,9/10/2024-9/13/2024,Kenton,Hardin County Fairgrounds,[Special Event],40.631205,-83.610080,NaN,"BP, BG, lipids",4,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kenton,7947,60.0
2,2024-09-21 00:00:00,Ada,Downtown Ada,[Special Event],40.769433,-83.823181,Harvest and Herb,BP + BG + lipids,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ada,5334,16.0
3,2024-09-21 00:00:00,Lima,Reading Park,[Special Event],40.742964,-84.120592,Mercy Block Party,BP,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lima,35579,30.0
4,2024-09-24 00:00:00,Lima,AAA Lima,[Special Event],40.748349,-84.148803,AAA Falls Day,BP + BMD,3,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lima,35579,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,2025-05-02 00:00:00,Ada,ONU Day of Giving,[Special Event],40.769433,-83.823181,HW,BP,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ada,5334,18.0
74,2025-05-06 00:00:00,Lima,Mercy Thrift Store,[Thrift store],40.743039,-84.111477,HealthWise,MHC,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lima,35579,4.0
75,2025-05-07 00:00:00,Lima,Christian Corner,[Food Bank],40.712793,-84.107995,HealthWise,MHC,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lima,35579,7.0
76,2025-05-08 00:00:00,Bluffton,Bluffton Library,[Library],40.892385,-83.892901,HealthWise,NaN,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bluffton,3967,3.0
77,2025-05-15 00:00:00,Kenton,HardinCrest,[Senior community],40.649799,-83.595708,HealthWise,MHC,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kenton,7947,3.0

## Look at Libraries

In [55]:
#libraryEvents = events.loc[events["Site Types"] == "Library",:]
#libraryEvents

## Look at Thrift Events

In [ ]:

thirft_events_mask = events["Site Types"].apply(lambda t : (t == "Thrift store").any())

thirftEvents = events.loc[thirft_events_mask,:]


pops = thirftEvents.loc[:,"pop"]
foot_traffic = thirftEvents.loc[:,"Foot traffic"]


plt.

thirftEvents

,Date,City,Physical location,Site Types,Latitude,Longitude,Organizer,Services offered,Total Pharmacists,Total APPE Students,...,Patients referred to Healthwise MC.1,Patients referred to other sites.1,Patients needing f/u.1,Patients who were seen at f/u.1,Patients not seen at f/u.1,New diagnosis noted at f/u.1,Interventions made at appointment.1,city,pop,Foot traffic
8,2024-10-25 00:00:00,Saint Marys,Agape,"[Food pantry, Thrift store]",40.546518,-84.370386,HealthWise,NaN,3,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Saint Marys,8397,0.0
9,2024-11-05 00:00:00,Lima,Mercy Thrift Store,[Thrift store],40.743039,-84.111477,HealthWise,MHC,3,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lima,35579,0.0
12,2024-11-12 00:00:00,Saint Marys,Agape,"[Food pantry, Thrift store]",40.546518,-84.370386,HealthWise,NaN,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Saint Marys,8397,4.0
20,2024-12-03 00:00:00,Lima,Mercy Thrift Store,[Thrift store],40.743039,-84.111477,HealthWise,MHC,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lima,35579,0.0
22,2024-12-10 00:00:00,Saint Marys,Agape,"[Food pantry, Thrift store]",40.546518,-84.370386,HealthWise,NaN,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Saint Marys,8397,0.0
28,2024-01-07 00:00:00,Lima,Mercy Thrift Store,[Thrift store],40.743039,-84.111477,HealthWise,NaN,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lima,35579,2.0
31,2025-01-14 00:00:00,Saint Marys,Agape,"[Food pantry, Thrift store]",40.546518,-84.370386,HealthWise,NaN,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Saint Marys,8397,0.0
33,2025-01-16 00:00:00,Kenton,HardinCrest,"[Food pantry, Thrift store]",40.649799,-83.595708,HealthWise,NaN,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kenton,7947,2.0
34,2025-01-23 00:00:00,Saint Marys,Agape,"[Food pantry, Thrift store]",40.546518,-84.370386,HealthWise,NaN,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Saint Marys,8397,1.0
40,2025-02-04 00:00:00,Lima,Mercy Thrift Store,[Thrift store],40.743039,-84.111477,HealthWise,NaN,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lima,35579,0.0
49,2025-02-27 00:00:00,Saint Marys,Agape,"[Food pantry, Thrift store]",40.546518,-84.370386,HealthWise,NaN,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Saint Marys,8397,0.0
50,2025-03-04 00:00:00,Lima,Mercy Thrift Store,[Thrift store],40.743039,-84.111477,HealthWise,NaN,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lima,35579,1.0
52,2025-03-06 00:00:00,Lima,Restore,[Thrift store],40.737793,-84.112412,HealthWise,MHC,3,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lima,35579,2.0
59,2025-03-27 00:00:00,Saint Marys,Agape,"[Food pantry, Thrift store]",40.546518,-84.370386,HealthWise,NaN,4,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Saint Marys,8397,0.0
60,2025-04-01 00:00:00,Lima,Mercy Thrift Store,[Thrift store],40.743039,-84.111477,MHC,MHC,3,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lima,35579,1.0
62,2025-04-03 00:00:00,Lima,Restore,[Thrift store],40.737793,-84.112412,HealthWise,MHC,3,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lima,35579,3.0
71,2024-04-24 00:00:00,Saint Marys,Agape,"[Food pantry, Thrift store]",40.546518,-84.370386,HealthWise,NaN,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Saint Marys,8397,2.0
72,2024-05-01 00:00:00,Lima,Restore,[Thrift store],40.737793,-84.112412,HealthWise,MHC,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lima,35579,8.0
74,2025-05-06 00:00:00,Lima,Mercy Thrift Store,[Thrift store],40.743039,-84.111477,HealthWise,MHC,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lima,35579,4.0